name: Documentation Validation

on:
  push:
    paths:
      - 'docs/**'
      - '.claude/**'
      - 'CLAUDE.md'
  pull_request:
    paths:
      - 'docs/**'
      - '.claude/**'
      - 'CLAUDE.md'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Markdown Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/markdown-link-check.json'
    
    - name: Check Claude Configuration
      run: |
        # Check if required Claude files exist
        if [ ! -f ".claude/project-rules.md" ]; then
          echo "Error: .claude/project-rules.md not found"
          exit 1
        fi
        
        if [ ! -f ".claude/context.md" ]; then
          echo "Error: .claude/context.md not found"
          exit 1
        fi
        
        if [ ! -f ".claude/instructions.md" ]; then
          echo "Error: .claude/instructions.md not found"
          exit 1
        fi
        
        echo "All Claude configuration files are present"
    
    - name: Validate Technical Spec
      run: |
        # Check if technical spec is up to date
        if grep -q "TODO" docs/technical-spec.md; then
          echo "Warning: TODO items found in technical-spec.md"
        fi
        
        # Check if all main sections exist
        sections=("아키텍처 개요" "도메인 모델" "애플리케이션 레이어" "인프라스트럭처 레이어")
        for section in "${sections[@]}"; do
          if ! grep -q "$section" docs/technical-spec.md; then
            echo "Error: Section '$section' not found in technical-spec.md"
            exit 1
          fi
        done
        
        echo "Technical specification validation passed"